# Generated by Django 6.0.7 on 2026-07-16 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_blog_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', '-created_at'], name='blog_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'featured'], name='blog_status_featured_idx'),
        ),
    ]
