# Generated by Django 6.0.6 on 2026-07-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('AI Development', 'AI Development'), ('UI/UX Design', 'UI/UX Design'), ('Digital Marketing', 'Digital Marketing'), ('SEO Optimization', 'SEO Optimization'), ('Cloud Solutions', 'Cloud Solutions'), ('Cyber Security', 'Cyber Security'), ('Another Service', 'Another Service')], max_length=100)),
                ('budget', models.CharField(choices=[('10k-20k', '₹10,000 - ₹20,000'), ('20k-50k', '₹20,000 - ₹50,000'), ('50k-1L', '₹50,000 - ₹1,00,000'), ('1L-5L', '₹1L - ₹5L'), ('5L+', '₹5L+')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
