# Generated by Django 6.0.7 on 2026-07-10 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='project_details',
            field=models.TextField(default=datetime.date(2026, 7, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Meeting Scheduled', 'Meeting Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='budget',
            field=models.CharField(choices=[('Under ₹25,000', 'Under ₹25,000'), ('10k-20k', '₹10,000 - ₹20,000'), ('20k-50k', '₹20,000 - ₹50,000'), ('50k-1L', '₹50,000 - ₹1,00,000'), ('1L-5L', '₹1L - ₹5L'), ('5L+', '₹5L+')], max_length=50),
        ),
    ]
