# Generated by Copilot on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmissionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_submitted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_submitted_at'],
            },
        ),
    ]
