# Generated by Django 6.0.7 on 2026-07-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('UI/UX Design', 'UI/UX Design'), ('Web Design', 'Web Design'), ('Mobile App', 'Mobile App'), ('Branding', 'Branding')], max_length=100)),
                ('image', models.ImageField(upload_to='case_study/')),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
