# Generated by Django 6.0.7 on 2026-07-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='seo_tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=250),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='category',
            field=models.CharField(choices=[('UI/UX Design', 'UI/UX Design'), ('Web Design', 'Web Design'), ('SEO', 'SEO'), ('Mobile App', 'Mobile App'), ('Branding', 'Branding')], max_length=100),
        ),
    ]
