# Generated by Django 6.0.7 on 2026-07-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0002_casestudy_seo_tags_alter_casestudy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='seo_tags',
            new_name='tags',
        ),
    ]
